from fastapi import HTTPException
from repositories.generators_repo import get_generator_by_id, list_generators as repo_list_generators


def get_generator(generator_id: int):
    row = get_generator_by_id(generator_id)
    if not row:
        raise HTTPException(status_code=404, detail="Generator not found")
    if isinstance(row, tuple):
        (
            id_, grid_id, idtag, name, code, bus_idtag, active, p, vset, qmin, qmax, pf,
            rdfid, action, comment, modelling_authority, commissioned_date, decommissioned_date,
            active_prof, mttf, mttr, capex, opex, build_status, cost, cost_prof, facility,
            technologies, scalable, shift_key, shift_key_prof, longitude, latitude, use_kw,
            conn, rms_model, bus_pos, control_bus, control_bus_prof, p_prof, pmin, pmin_prof,
            pmax, pmax_prof, srap_enabled, srap_enabled_prof, is_controlled, pf_prof, vset_prof,
            snom, qmin_prof, qmax_prof, use_reactive_power_curve, q_curve, r1, x1, r0, x0, r2, x2,
            cost2, cost2_prof, cost0, cost0_prof, startupcost, shutdowncost, mintimeup, mintimedown,
            rampup, rampdown, enabled_dispatch, emissions, fuels,
        ) = row
        return {
            "id": id_,
            "grid_id": grid_id,
            "idtag": idtag,
            "name": name,
            "code": code,
            "bus_idtag": bus_idtag,
            "active": active,
            "p": p,
            "vset": vset,
            "qmin": qmin,
            "qmax": qmax,
            "pf": pf,
            "rdfid": rdfid,
            "action": action,
            "comment": comment,
            "modelling_authority": modelling_authority,
            "commissioned_date": commissioned_date,
            "decommissioned_date": decommissioned_date,
            "active_prof": active_prof,
            "mttf": mttf,
            "mttr": mttr,
            "capex": capex,
            "opex": opex,
            "build_status": build_status,
            "cost": cost,
            "cost_prof": cost_prof,
            "facility": facility,
            "technologies": technologies,
            "scalable": scalable,
            "shift_key": shift_key,
            "shift_key_prof": shift_key_prof,
            "longitude": longitude,
            "latitude": latitude,
            "use_kw": use_kw,
            "conn": conn,
            "rms_model": rms_model,
            "bus_pos": bus_pos,
            "control_bus": control_bus,
            "control_bus_prof": control_bus_prof,
            "p_prof": p_prof,
            "pmin": pmin,
            "pmin_prof": pmin_prof,
            "pmax": pmax,
            "pmax_prof": pmax_prof,
            "srap_enabled": srap_enabled,
            "srap_enabled_prof": srap_enabled_prof,
            "is_controlled": is_controlled,
            "pf_prof": pf_prof,
            "vset_prof": vset_prof,
            "snom": snom,
            "qmin_prof": qmin_prof,
            "qmax_prof": qmax_prof,
            "use_reactive_power_curve": use_reactive_power_curve,
            "q_curve": q_curve,
            "r1": r1,
            "x1": x1,
            "r0": r0,
            "x0": x0,
            "r2": r2,
            "x2": x2,
            "cost2": cost2,
            "cost2_prof": cost2_prof,
            "cost0": cost0,
            "cost0_prof": cost0_prof,
            "startupcost": startupcost,
            "shutdowncost": shutdowncost,
            "mintimeup": mintimeup,
            "mintimedown": mintimedown,
            "rampup": rampup,
            "rampdown": rampdown,
            "enabled_dispatch": enabled_dispatch,
            "emissions": emissions,
            "fuels": fuels,
        }
    return row


def list_generators():
    rows = repo_list_generators()
    if not rows:
        return []
    normalized = []
    for row in rows:
        if isinstance(row, tuple):
            (
                id_, grid_id, idtag, name, code, bus_idtag, active, p, vset, qmin, qmax, pf,
                rdfid, action, comment, modelling_authority, commissioned_date, decommissioned_date,
                active_prof, mttf, mttr, capex, opex, build_status, cost, cost_prof, facility,
                technologies, scalable, shift_key, shift_key_prof, longitude, latitude, use_kw,
                conn, rms_model, bus_pos, control_bus, control_bus_prof, p_prof, pmin, pmin_prof,
                pmax, pmax_prof, srap_enabled, srap_enabled_prof, is_controlled, pf_prof, vset_prof,
                snom, qmin_prof, qmax_prof, use_reactive_power_curve, q_curve, r1, x1, r0, x0, r2, x2,
                cost2, cost2_prof, cost0, cost0_prof, startupcost, shutdowncost, mintimeup, mintimedown,
                rampup, rampdown, enabled_dispatch, emissions, fuels,
            ) = row
            normalized.append({
                "id": id_,
                "grid_id": grid_id,
                "idtag": idtag,
                "name": name,
                "code": code,
                "bus_idtag": bus_idtag,
                "active": active,
                "p": p,
                "vset": vset,
                "qmin": qmin,
                "qmax": qmax,
                "pf": pf,
                "rdfid": rdfid,
                "action": action,
                "comment": comment,
                "modelling_authority": modelling_authority,
                "commissioned_date": commissioned_date,
                "decommissioned_date": decommissioned_date,
                "active_prof": active_prof,
                "mttf": mttf,
                "mttr": mttr,
                "capex": capex,
                "opex": opex,
                "build_status": build_status,
                "cost": cost,
                "cost_prof": cost_prof,
                "facility": facility,
                "technologies": technologies,
                "scalable": scalable,
                "shift_key": shift_key,
                "shift_key_prof": shift_key_prof,
                "longitude": longitude,
                "latitude": latitude,
                "use_kw": use_kw,
                "conn": conn,
                "rms_model": rms_model,
                "bus_pos": bus_pos,
                "control_bus": control_bus,
                "control_bus_prof": control_bus_prof,
                "p_prof": p_prof,
                "pmin": pmin,
                "pmin_prof": pmin_prof,
                "pmax": pmax,
                "pmax_prof": pmax_prof,
                "srap_enabled": srap_enabled,
                "srap_enabled_prof": srap_enabled_prof,
                "is_controlled": is_controlled,
                "pf_prof": pf_prof,
                "vset_prof": vset_prof,
                "snom": snom,
                "qmin_prof": qmin_prof,
                "qmax_prof": qmax_prof,
                "use_reactive_power_curve": use_reactive_power_curve,
                "q_curve": q_curve,
                "r1": r1,
                "x1": x1,
                "r0": r0,
                "x0": x0,
                "r2": r2,
                "x2": x2,
                "cost2": cost2,
                "cost2_prof": cost2_prof,
                "cost0": cost0,
                "cost0_prof": cost0_prof,
                "startupcost": startupcost,
                "shutdowncost": shutdowncost,
                "mintimeup": mintimeup,
                "mintimedown": mintimedown,
                "rampup": rampup,
                "rampdown": rampdown,
                "enabled_dispatch": enabled_dispatch,
                "emissions": emissions,
                "fuels": fuels,
            })
        else:
            normalized.append(row)
    return normalized
