from fastapi import HTTPException
from repositories.transformers2w_repo import get_transformer2w_by_id, list_transformers2w as repo_list_transformers2w


def get_transformer2w(transformer_id: int):
    row = get_transformer2w_by_id(transformer_id)
    if not row:
        raise HTTPException(status_code=404, detail="Transformer2W not found")
    if isinstance(row, tuple):
        (
            id_, grid_id, idtag, name, code, bus_from_idtag, bus_to_idtag, active,
            r, x, g, b, hv, lv, sn,
            rdfid, action, comment, modelling_authority, commissioned_date, decommissioned_date,
            active_prof, reducible, rate, rate_prof, contingency_factor, contingency_factor_prof,
            protection_rating_factor, protection_rating_factor_prof, monitor_loading, mttf, mttr,
            cost, cost_prof, build_status, capex, opex, tx_group, color, rms_model,
            bus_from_pos, bus_to_pos, r0, x0, g0, b0, r2, x2, g2, b2, tolerance,
            tap_changer, tap_module, tap_module_prof, tap_module_max, tap_module_min,
            tap_module_control_mode, tap_module_control_mode_prof, vset, vset_prof,
            qset, qset_prof, regulation_bus, tap_phase, tap_phase_prof, tap_phase_max,
            tap_phase_min, tap_phase_control_mode, tap_phase_control_mode_prof, pset,
            pset_prof, temp_base, temp_oper, temp_oper_prof, alpha, pcu, pfe, i0, vsc,
            conn, conn_f, conn_t, vector_group_number, template,
        ) = row
        return {
            "id": id_,
            "grid_id": grid_id,
            "idtag": idtag,
            "name": name,
            "code": code,
            "bus_from_idtag": bus_from_idtag,
            "bus_to_idtag": bus_to_idtag,
            "active": active,
            "r": r,
            "x": x,
            "g": g,
            "b": b,
            "hv": hv,
            "lv": lv,
            "sn": sn,
            "rdfid": rdfid,
            "action": action,
            "comment": comment,
            "modelling_authority": modelling_authority,
            "commissioned_date": commissioned_date,
            "decommissioned_date": decommissioned_date,
            "active_prof": active_prof,
            "reducible": reducible,
            "rate": rate,
            "rate_prof": rate_prof,
            "contingency_factor": contingency_factor,
            "contingency_factor_prof": contingency_factor_prof,
            "protection_rating_factor": protection_rating_factor,
            "protection_rating_factor_prof": protection_rating_factor_prof,
            "monitor_loading": monitor_loading,
            "mttf": mttf,
            "mttr": mttr,
            "cost": cost,
            "cost_prof": cost_prof,
            "build_status": build_status,
            "capex": capex,
            "opex": opex,
            "tx_group": tx_group,
            "color": color,
            "rms_model": rms_model,
            "bus_from_pos": bus_from_pos,
            "bus_to_pos": bus_to_pos,
            "r0": r0,
            "x0": x0,
            "g0": g0,
            "b0": b0,
            "r2": r2,
            "x2": x2,
            "g2": g2,
            "b2": b2,
            "tolerance": tolerance,
            "tap_changer": tap_changer,
            "tap_module": tap_module,
            "tap_module_prof": tap_module_prof,
            "tap_module_max": tap_module_max,
            "tap_module_min": tap_module_min,
            "tap_module_control_mode": tap_module_control_mode,
            "tap_module_control_mode_prof": tap_module_control_mode_prof,
            "vset": vset,
            "vset_prof": vset_prof,
            "qset": qset,
            "qset_prof": qset_prof,
            "regulation_bus": regulation_bus,
            "tap_phase": tap_phase,
            "tap_phase_prof": tap_phase_prof,
            "tap_phase_max": tap_phase_max,
            "tap_phase_min": tap_phase_min,
            "tap_phase_control_mode": tap_phase_control_mode,
            "tap_phase_control_mode_prof": tap_phase_control_mode_prof,
            "pset": pset,
            "pset_prof": pset_prof,
            "temp_base": temp_base,
            "temp_oper": temp_oper,
            "temp_oper_prof": temp_oper_prof,
            "alpha": alpha,
            "pcu": pcu,
            "pfe": pfe,
            "i0": i0,
            "vsc": vsc,
            "conn": conn,
            "conn_f": conn_f,
            "conn_t": conn_t,
            "vector_group_number": vector_group_number,
            "template": template,
        }
    return row


def list_transformers2w():
    rows = repo_list_transformers2w()
    if not rows:
        return []
    normalized = []
    for row in rows:
        if isinstance(row, tuple):
            (
                id_, grid_id, idtag, name, code, bus_from_idtag, bus_to_idtag, active,
                r, x, g, b, hv, lv, sn,
                rdfid, action, comment, modelling_authority, commissioned_date, decommissioned_date,
                active_prof, reducible, rate, rate_prof, contingency_factor, contingency_factor_prof,
                protection_rating_factor, protection_rating_factor_prof, monitor_loading, mttf, mttr,
                cost, cost_prof, build_status, capex, opex, tx_group, color, rms_model,
                bus_from_pos, bus_to_pos, r0, x0, g0, b0, r2, x2, g2, b2, tolerance,
                tap_changer, tap_module, tap_module_prof, tap_module_max, tap_module_min,
                tap_module_control_mode, tap_module_control_mode_prof, vset, vset_prof,
                qset, qset_prof, regulation_bus, tap_phase, tap_phase_prof, tap_phase_max,
                tap_phase_min, tap_phase_control_mode, tap_phase_control_mode_prof, pset,
                pset_prof, temp_base, temp_oper, temp_oper_prof, alpha, pcu, pfe, i0, vsc,
                conn, conn_f, conn_t, vector_group_number, template,
            ) = row
            normalized.append({
                "id": id_,
                "grid_id": grid_id,
                "idtag": idtag,
                "name": name,
                "code": code,
                "bus_from_idtag": bus_from_idtag,
                "bus_to_idtag": bus_to_idtag,
                "active": active,
                "r": r,
                "x": x,
                "g": g,
                "b": b,
                "hv": hv,
                "lv": lv,
                "sn": sn,
                "rdfid": rdfid,
                "action": action,
                "comment": comment,
                "modelling_authority": modelling_authority,
                "commissioned_date": commissioned_date,
                "decommissioned_date": decommissioned_date,
                "active_prof": active_prof,
                "reducible": reducible,
                "rate": rate,
                "rate_prof": rate_prof,
                "contingency_factor": contingency_factor,
                "contingency_factor_prof": contingency_factor_prof,
                "protection_rating_factor": protection_rating_factor,
                "protection_rating_factor_prof": protection_rating_factor_prof,
                "monitor_loading": monitor_loading,
                "mttf": mttf,
                "mttr": mttr,
                "cost": cost,
                "cost_prof": cost_prof,
                "build_status": build_status,
                "capex": capex,
                "opex": opex,
                "tx_group": tx_group,
                "color": color,
                "rms_model": rms_model,
                "bus_from_pos": bus_from_pos,
                "bus_to_pos": bus_to_pos,
                "r0": r0,
                "x0": x0,
                "g0": g0,
                "b0": b0,
                "r2": r2,
                "x2": x2,
                "g2": g2,
                "b2": b2,
                "tolerance": tolerance,
                "tap_changer": tap_changer,
                "tap_module": tap_module,
                "tap_module_prof": tap_module_prof,
                "tap_module_max": tap_module_max,
                "tap_module_min": tap_module_min,
                "tap_module_control_mode": tap_module_control_mode,
                "tap_module_control_mode_prof": tap_module_control_mode_prof,
                "vset": vset,
                "vset_prof": vset_prof,
                "qset": qset,
                "qset_prof": qset_prof,
                "regulation_bus": regulation_bus,
                "tap_phase": tap_phase,
                "tap_phase_prof": tap_phase_prof,
                "tap_phase_max": tap_phase_max,
                "tap_phase_min": tap_phase_min,
                "tap_phase_control_mode": tap_phase_control_mode,
                "tap_phase_control_mode_prof": tap_phase_control_mode_prof,
                "pset": pset,
                "pset_prof": pset_prof,
                "temp_base": temp_base,
                "temp_oper": temp_oper,
                "temp_oper_prof": temp_oper_prof,
                "alpha": alpha,
                "pcu": pcu,
                "pfe": pfe,
                "i0": i0,
                "vsc": vsc,
                "conn": conn,
                "conn_f": conn_f,
                "conn_t": conn_t,
                "vector_group_number": vector_group_number,
                "template": template,
            })
        else:
            normalized.append(row)
    return normalized
